# Generated by Django 4.2.20 on 2025-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_event_manager',
            field=models.BooleanField(default=False, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_speaker',
            field=models.BooleanField(default=False, verbose_name='Докладчик'),
        ),
    ]
