# Generated by Django 4.2.20 on 2025-05-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0002_participant_is_event_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_event_manager',
            field=models.BooleanField(default=False, verbose_name='Управляющий мероприятием'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='speakers', to='events_bot.event'),
        ),
    ]
