# Generated by Django 4.2.20 on 2025-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0007_alter_speaker_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_first_in_networking',
            field=models.BooleanField(default=False, verbose_name='Первый пользователь в знакомствах'),
        ),
        migrations.AddField(
            model_name='participant',
            name='notified_about_newcommers',
            field=models.BooleanField(default=False, verbose_name='Уведомлён о новых анкетах'),
        ),
    ]
