# Generated by Django 4.2.20 on 2025-05-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0007_alter_speaker_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
    ]
