# Generated by Django 4.2.20 on 2025-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0008_participant_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='events_bot.event', verbose_name='Зарегистрированные мероприятия'),
        ),
    ]
